### ISSUE TITLE
Previous PR - Bucket Policy

### ISSUE THREAD

**Issue by SherrinRaji** [addu390/licensing-as-a-platform#8]
Bucket Policy:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "StatementPrefixDeny",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:GetObject",
            "Resource": [
                "arn:aws:s3:::laap-static-files/static/*",
                "arn:aws:s3:::laap-static-files/static"
            ]
        }
    ]
}

**Comment by addu390** [comment]
Acknowledged!
